#KERNELDIR = /home/yfpan/Workspace/linux-3.5-20140314
#PWD := $(shell pwd)
#CROSS_COMPILE = /home/yfpan/Workspace/toolschain/4.5.1/bin/arm-linux-
#CC    = $(CROSS_COMPILE)gcc
#
gf-milanf-tee-dev-objs :=  gf_spi.o platform.o netlink.o
obj-$(CONFIG_FINGERPRINT_GOODIX) := gf-milanf-tee-dev.o

#modules:
#	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules
#clean:
#	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions *.symvers *.order
#.PHONY: modules clean
